### ISSUE TITLE
Crash by starting of Minecraft 

### ISSUE THREAD

**Issue by Titoo8899** [exzhawk/AutoLoadLastWorld#1]
Hi,
my Minecraft game crash then all Mods was load and the game the menu show will. It freeze in a white Background and make not more. I hope this Crash Report help to fix the Problem.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SFMLLoadingPlugin (somnia-1.10.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  CoreMod (scarecrowsterritory-1.0.4-mc1.12.jar)
  McLib core mod (mclib-2.2-1.12.2.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  ForgedCarpetCore (forged-carpet-1.12.2-1.3.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 2/27/21 7:49 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:450)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 809017152 bytes (771 MB) / 2181038080 bytes (2080 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 55 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                               | Version          | Source                                              | Signature                                |
	|:------ |:-------------------------------- |:---------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                        | 1.12.2           | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                              | 9.42             | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                              | 8.0.99.99        | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                            | 14.23.5.2854     | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | somniacore                       | 2.0.0            | minecraft.jar                                       | None                                     |
	| LCHIJA | supermartijn642configlib         | 1.0.3            | supermartijn642configlib-1.0.3-mc1.12.jar           | None                                     |
	| LCHIJA | scarecrowsterritory              | 1.0.4            | scarecrowsterritory-1.0.4-mc1.12.jar                | None                                     |
	| LCHIJA | securitycraft                    | v1.8.21          | [1.12.2]+SecurityCraft+v1.8.21.jar                  | None                                     |
	| LCHIJA | collective                       | 1.68             | collective-1.12.2-1.68.jar                          | None                                     |
	| LCHIJA | advancementscreenshot            | 1.2              | advancementscreenshot_1.12.2-1.2.jar                | None                                     |
	| LCHIJA | airhop                           | 1.1.2            | AirHop-v1.2-1.12.2.jar                              | None                                     |
	| LCHIJA | airportlight                     | [1.12.2]-[1.4.2] | AirPort1.12.2-[1.12.2]-[1.4.2].jar                  | None                                     |
	| LCHIJA | aquaacrobatics                   | 1.3.5            | AquaAcrobatics-v1.3.5-1.12.2.jar                    | None                                     |
	| LCHIJA | autoloadlastworld                | 1.0              | autoloadlastworld-1.1.jar                           | None                                     |
	| LCHIJA | camelotcraftsoundpack            | 1.0.0            | camelotcraft soundpack.jar                          | None                                     |
	| LCHIJA | checklist                        | 1.0.2            | Checklist-1.12.2-1.0.2.jar                          | None                                     |
	| LCHIJA | creativeblockreplacer            | 1.3              | creativeblockreplacer_1.12.2-1.3.jar                | None                                     |
	| LCHIJA | sawtastic                        | 1.0              | demo_2_sawtastic_1.0_MC_1.12.2.jar                  | None                                     |
	| LCHIJA | elenaidodge2                     | 1.0.7            | ElenaiDodge2-1.12.2-2.0.7.jar                       | None                                     |
	| LCHIJA | essensialmodernconstructionblock | 1.1.0            | EMCB+HD+1.12.2+v1.1.0.jar                           | None                                     |
	| LCHIJA | mclib                            | 2.2              | mclib-2.2-1.12.2.jar                                | None                                     |
	| LCHIJA | emoticons                        | 0.7              | emoticons-0.7-1.12.2-dist.jar                       | None                                     |
	| LCHIJA | fcl                              | 1.12.60          | Fexcraft+Common+Library-1.12.60.jar                 | None                                     |
	| LCHIJA | tmt                              | 1.12             | Fexcraft+Common+Library-1.12.60.jar                 | None                                     |
	| LCHIJA | firstjoinmessage                 | 1.1              | firstjoinmessage_1.12.2-1.1.jar                     | None                                     |
	| LCHIJA | forgedcarpet                     | 1.3.2            | forged-carpet-1.12.2-1.3.2.jar                      | 96fc52aa67093ae7204767021b34156ab2e41975 |
	| LCHIJA | fwparchitecturalenhancements     | 1.0.0            | FWPArchitecturalEnhancements_v2.2.jar               | None                                     |
	| LCHIJA | girsignals                       | 1.0.0            | GIRSignals-1.0.216.jar                              | None                                     |
	| LCHIJA | goodmorning                      | 1.12.2-1.2       | GoodMorning-1.12.2-1.2.jar                          | None                                     |
	| LCHIJA | guiclock                         | 2.2              | guiclock_1.12.2-2.2.jar                             | None                                     |
	| LCHIJA | guicompass                       | 1.4              | guicompass_1.12.2-1.4.jar                           | None                                     |
	| LCHIJA | handoveryouritems                | 1.0              | handoveryouritems_1.12.2-1.0.jar                    | None                                     |
	| LCHIJA | mts                              | 19.13.1          | Immersive+Vehicles-1.12.2-19.13.1.jar               | None                                     |
	| LCHIJA | inventoryhud                     | 3.2.0            | InventoryHud_1.12.2.forge-3.2.1.jar                 | None                                     |
	| LCHIJA | timecore                         | 1.0.1.1          | TimeCore-1.12.2-1.0.1.1.jar                         | None                                     |
	| LCHIJA | lootgames                        | 1.0.3.1          | LootGames-1.12.2-1.0.3.1.jar                        | None                                     |
	| LCHIJA | lottweaks                        | 2.0.4            | LotTweaks-mc1.12.2-version-2.0.4.jar                | None                                     |
	| LCHIJA | melvinssignpack                  | 1.0.0            | Melvins_Simple_Sign_Pack-Release-1.0.jar            | None                                     |
	| LCHIJA | naturaldecormod                  | 1.4.21           | Natural+Decor+Mod+1.12+II+V1.4.21.jar               | None                                     |
	| LCHIJA | nutrition                        | 4.6.1            | Nutrition-1.12.2-4.6.1.jar                          | None                                     |
	| LCHIJA | zblock                           | 1.2021.02.06     | pushable_puzzle_blocks-1.2021.02.07.jar             | None                                     |
	| LCHIJA | respawntimer                     | $version         | respawntimer-1.12.2-2.0.2.0.jar                     | None                                     |
	| LCHIJA | saveandloadinventories           | 1.2              | saveandloadinventories_1.12.2-1.2.jar               | None                                     |
	| LCHIJA | scm                              | 1.0.04a          | SCM-v1.12.2-1.0.04a.jar                             | None                                     |
	| LCHIJA | simpledifficulty                 | 0.3.5            | SimpleDifficulty-1.12.2-0.3.5.jar                   | None                                     |
	| LCHIJA | simple_mud_mod                   | 1.0.0            | SimpleMudMod.jar                                    | None                                     |
	| LCHIJA | softerhaybales                   | 1.2              | softerhaybales_1.12.2-1.2.jar                       | None                                     |
	| LCHIJA | somnia                           | 1.10             | somnia-1.10.jar                                     | None                                     |
	| LCHIJA | splatcraft                       | 2.2.2            | Splatcraft-2.2.2.jar                                | None                                     |
	| LCHIJA | tickratechanger                  | 1.0.14           | TickrateChanger-1.0.14.jar                          | None                                     |
	| LCHIJA | timeflies                        | 1.0.0            | Time+Flies+1.12.2+v2.0.jar                          | None                                     |
	| LCHIJA | vm                               | 1.0              | TimeStop-1.41.jar                                   | None                                     |
	| LCHIJA | unuparts                         | 4.0.0            | UNU+Parts+Pack+[MTS]+1.12.2-19.12.0-4.0.0-BETA4.jar | None                                     |
	| LCHIJA | vanitymod                        | 1.2.0            | vanitymod-1.2.0-1.12.2.jar                          | None                                     |
	| UD     | mclib_core                       | 2.2              | minecraft.jar                                       | None                                     |

	Loaded coremods (and transformers): 
SFMLLoadingPlugin (somnia-1.10.jar)
  com.kingrunes.somnia.asm.SClassTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
CoreMod (scarecrowsterritory-1.0.4-mc1.12.jar)
  
McLib core mod (mclib-2.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  
ForgedCarpetCore (forged-carpet-1.12.2-1.3.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Titoo8899** [comment]
I have a second test make with only your mod and the same think. The Game Freeze with white background and the game crash. I play with Forge 1.12.2 - 14.23.5.2854 the last and newest Forge 1.12.2 Version what it give.

**Comment by exzhawk** [comment]
The crashing report may indicate that you have a corrupt chunk. see https://www.reddit.com/r/Minecraft/comments/835uz4/help_with_modded_client_crash/ if it applies.

And try both of the following to help me identify the problem:
1. remove auto load last world mod and try loading the last world manually. see if the game freeze/crash.
2. create a NEW minecraft instance with forge and only auto load last world mod, create new world, save and quit. then re-launch the instance. If it freeze/crash, post logs and crash report.

**Comment by Titoo8899** [comment]
I have your Methode make and the same Problem.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/27/21 8:36 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:450)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 296526856 bytes (282 MB) / 536870912 bytes (512 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                        | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | autoloadlastworld | 1.0          | autoloadlastworld-1.1.jar     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Titoo8899** [comment]
I hope you find a fix to fix this tick Problem in your mod. So can no one play with this mod.

**Comment by exzhawk** [comment]
which method?
Please try both and describe both of them

**Comment by Titoo8899** [comment]
I have as first the autolastworld mod remove and then manually load my last world and it have not freeze or crash.
Then have I and I have a good Computer a new Minecraft instance with forge make and your 2 Methode make and the game crash by the first load. It is not a Problem of Forge or the other mods what I have. It is a config Problem or a fail in the codes of your mod. 

It is only a Problem in your Mod. I hope you can a fix make of your Mod.

The Config of your mod have this by me:

# Configuration file

general {
    # Disable auto load world
    B:disabled=false

    # Only auto load world at the first time
    B:firstOnly=true
}


This show normal and what you say you can the first time make on false in your Mod Discribtion. I hope you find the Bug in your Mod Codes.

**Comment by Titoo8899** [comment]
You become a Link to a Video with my Problem. This is easy and better to see what the Problem is.

**Comment by Titoo8899** [comment]
Her the Link to the Problem of your Mod I hope it help you. Link: https://www.youtube.com/watch?v=44bNoCt0D14

**Comment by exzhawk** [comment]
This is so weird... But I can't reproduce it. So please follow the steps below again to help me debug:
Create a NEW minecraft instance with forge only.
Launch the game, click the singleplayer button, and make sure you do NOT have any saved world in this instance.
Quit the game.
Add auto load last world mod.
Launch the game. Because there is no saved world, you should see the main menu. 
Create a new world, save and quit the game.
Launch the game again and see if it crash.

The video is helpful, please record all the steps above as a video if convenient.

**Comment by Titoo8899** [comment]
I have your Methode test and my Video have all this. And it work but I hope you can in a next update the world what as last open was with your mod open. I have 2 world with name "AutoLoadLastWorld1" and "AutoLoadLastWorld2" create but only the 1 was load then I save and quit and then open world 2 and save this with a actually time have I hope this World 2 was load but no world 1 was load. I hope you can a config or so make with the last save of a world is loading by next time not what we as first world create.

Link to the video: https://www.youtube.com/watch?v=us61BwhE_ws

**Comment by Titoo8899** [comment]
Your Mod is more a you have one world and this can be load and skip the Menü but I hope you can this more in the line of you have more as one world and the last world what we have save is the map what by the next start with no menü direct open

**Comment by exzhawk** [comment]
Nice catch. The mod actually loaded the oldest world instead of the last one. Version 1.2 (https://www.curseforge.com/minecraft/mc-mods/auto-load-last-world/files/3221792) should fix this and always load the last world. Try it to see if it works as expected.

And glad to see you solved the crash.

**Comment by Titoo8899** [comment]
Hi,
okay I will this check and a video make with this new Update.

**Comment by Titoo8899** [comment]
so I have testet and it work the last world what I save load by next start of minecraft. Thank you for this. I have check it and the last 1.12.2 Version of Just Enough Items work not with your Mod. Look the Picture what it say then I will it load. Link: https://drive.google.com/file/d/1_ewfY9Dh1uXUtfG6h0I7BeL5OioBY9v-/view?usp=sharing

Hope you can fix this and in the next update a compatible of this make.

**Comment by exzhawk** [comment]
That is JustEnoughIDs mod rather than  Just Enough Items.
I think you might load the world without JustEnoughIDs, causing the warning screen you posted.
ref: https://www.curseforge.com/minecraft/mc-mods/jeid/files/2583307

You may follow the steps to identify the problem:
Create a NEW Minecraft instance with forge, auto load last world mod, and JustEnoughIDs mod only.
Launch the game while holding one of ctrl/alt/shift buttons to prevent auto load last world mod working until you see the main menu, click the singleplayer button, and make sure you do NOT have any saved world in this instance.
Create a new world, save and quit the game.
Launch the game again and see if it loads the last world and/or show that warning screen.

**Comment by Titoo8899** [comment]
yes okay it work. I have the IDs Mod deleted and yes it work fine. But one little think. Can you a Button in the Menü Area make who we can start the last world. I mean 2 ways to open the last world per this methode in the load of Minecraft and the second way with a button in the menü. I hope you can so what make. I find it cool then the Person in the menü a little button have for load last world.

**Comment by Titoo8899** [comment]
and can you look for a compatible of your mod and the JustEnoughIDs Mod in the future?

**Comment by exzhawk** [comment]
Sorry, but currently I don't have plans to manipulate main menu.
If you insist on adding buttons to main menu, try this mod
https://www.curseforge.com/minecraft/mc-mods/custom-main-menu
Create a world with a certain name, then write config with loadWorld action to load the world. Not exactly same as always loading last world, but usable as always loading one world.

**Comment by exzhawk** [comment]
> and can you look for a compatible of your mod and the JustEnoughIDs Mod in the future?

Try the steps I mentioned before. You'll notice it's compatible.
